name: Create Changes

on:
  schedule:
    - cron: 0 11 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: Prepare Flutter SDK
        uses: subosito/flutter-action@v1
      - run: flutter channel dev
        name: Switch Flutter channel
      - run: cd tools/changes && flutter pub get
        name: Get dependencies
      - run: cd tools/changes && dart main.dart